apiVersion: v1
name: exposecontroller
description: exposecontroller chart that runs on kubernetes
version: 1.0.18
keywords:
  - exposecontroller
  - kubernetes
home: https://github.com/stakater-charts/exposecontroller
maintainers:
- name: Stakater
  email: stakater@aurorasolutions.io
